services:
  web:
    build:
      context: ./
    command: npm start
    restart: unless-stopped
    ports:
      - "20000:${PORT}"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DEBUG: nodejs-docker-express:*