version: '3.3'
services:
  web:
    build:
      context: ./
    command: npm start
    restart: always
    ports:
      - "20000:3000"
    environment:
      NODE_ENV: production
      DEBUG: nodejs-docker-express:*